apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-pod
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: kube
    spec:
      containers:
      - name: week-23
        image: nginx
        imagePullPolicy: Never
  selector:
    matchLabels:
      app: kube